{% set name = "zarr" %}
{% set version = "3.1.6" %}
{% set ignore_tests = " --ignore=tests/test_properties.py" %}

# Tests randomly failed on different platforms. Ignore tests with deadline.
#>               raise DeadlineExceeded(
#                    datetime.timedelta(seconds=runtime), self.settings.deadline
#                )
#E               hypothesis.errors.DeadlineExceeded: Test took 245.69ms, which exceeds the deadline of 200.00ms
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d95e72cbea4b90e9a70679468b8266400331756232576ae2b43400ac5108d0eb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<311]
  entry_points:
    - zarr = zarr._cli.cli:app

requirements:
  host:
    - python
    - pip
    - hatchling >=1.27.0
    - hatch-vcs
  run:
    - python
    - packaging >=22.0
    - numpy >=1.26
    - numcodecs >=0.14
    - crc32c >=2.7
    - typing-extensions >=4.9
    - donfig >=0.8
    # cli app
    - typer
  run_constrained:
    - fsspec >=2023.10.0

test:
  source_files:
    - tests
  imports:
    - zarr
    - zarr._version
    - zarr.abc
    - zarr.api
    - zarr.buffer
    - zarr.codecs
    - zarr.core
    - zarr.dtype
    - zarr.errors
    - zarr.metadata
    - zarr.registry
    - zarr.storage
    - zarr.testing
  commands:
    - pip check
    - zarr --help
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -ra -vv {{ ignore_tests }} tests --asyncio-mode=auto
  requires:
    - pip
    - coverage >=7.10
    - pytest <8.4
    - pytest-asyncio
    - botocore
    - s3fs
    - requests
    - hypothesis
    - typer
    - numpydoc
    - tomlkit

about:
  home: https://github.com/zarr-developers/zarr-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An implementation of chunked, compressed, N-dimensional arrays for Python.
  description: |
    Zarr is a format for the storage of chunked, compressed, N-dimensional arrays.
    These documents describe the Zarr format and its Python implementation.
  dev_url: https://github.com/zarr-developers/zarr-python
  doc_url: https://zarr.readthedocs.io

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
